services:

  data_db:
    image: mysql:8
    container_name: data_database
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: datadatabase
    ports:
      - "3307:3306"
    volumes:
      - ./tabd.sql:/docker-entrypoint-initdb.d/tabd.sql
      - mysqldata2:/var/lib/mysql
    networks:
      - app_data_network

  user_db:
    image: mysql:8
    container_name: user_database
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: userdatabase
    ports:
      - "3306:3306"
    volumes:
      - ./tabu.sql:/docker-entrypoint-initdb.d/tabu.sql
      - mysqldata:/var/lib/mysql
    networks:
      - app_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app_kafka_network
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/127.0.0.1/2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # ------------------- START OF FIX -------------------
      KAFKA_LISTENERS: INTERNAL://kafka:29092,PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # ------------------- END OF FIX ---------------------
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - app_kafka_network
    healthcheck:
      test: ["CMD", "bash", "-c", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 10s
      retries: 10

  data_collector:
    build: ./DataCollector
    container_name: data_collector
    depends_on:
      kafka:
        condition: service_started
      data_db:
        condition: service_started
      user_manag:
        condition: service_started
    environment:
      DB_HOST: data_db
      DB_USER: user
      DB_PASS: pass
      DB_NAME: datadatabase
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      KAFKA_TOPIC_ALERT_SYSTEM: "to-alert-system"
    ports:
      - "5001:5001"
    volumes:
      - ./proto:/proto
    networks:
      - app_kafka_network
      - app_data_network
      - app_network

  user_manag:
    build: ./UserManager
    container_name: user_manager
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: userdatabase
    volumes:
      - ./proto:/proto
    depends_on:
      - user_db
    networks:
      - app_network

  user_grpc:
    build: ./UserManager
    container_name: user_grpc
    command: python grpc_server.py
    environment:
      MYSQL_HOST: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: userdatabase
    networks:
      - app_network
    depends_on:
      - user_db

  api_gateway:
    build: ./nginx
    container_name: api_gateway
    depends_on:
      - data_collector
      - user_manag
      - user_grpc
    ports:
      - "8080:80"
    networks:
      - app_network
      - app_data_network

  alert_system:
    build: ./Alert
    container_name: alert_system
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      KAFKA_TOPIC_CONSUME: "to-alert-system"
      KAFKA_TOPIC_PRODUCE: "to-notifier"
    networks:
      - app_kafka_network

  notifier_system:
    build: ./Notify
    container_name: notifier_system
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      KAFKA_TOPIC_CONSUME: "to-notifier"
      SMTP_SERVER: smtp_relay
      SMTP_PORT: 25
    networks:
      - app_kafka_network

  smtp_relay:
    image: namshi/smtp
    container_name: smtp_relay_email
    ports:
      - "2525:25"
    networks:
      - app_kafka_network

volumes:
  mysqldata:
  mysqldata2:

networks:
  app_network:
  app_data_network:
  app_kafka_network: