services:

  data_collector:
    build: ./DataCollector
    container_name: data_collector
    depends_on:
      - data_db
      - user_manag
      - kafka
    environment:
      DB_HOST: data_db
      DB_USER: user
      DB_PASS: pass
      DB_NAME: datadatabase
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_TOPIC_ALERT_SYSTEM: "to-alert-system"
    ports:
      - "5001:5001"
    volumes:
      - ./proto:/proto
    networks:
      - app_data_network
      - app_network

  data_db:
    image: mysql:8
    container_name: data_database
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: datadatabase
    ports:
      - "3307:3306"
    volumes:
      - ./tabd.sql:/docker-entrypoint-initdb.d/tabd.sql
      - mysqldata2:/var/lib/mysql
    networks:
      - app_data_network

  user_manag:
    build: ./UserManager
    container_name: user_manager
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: userdatabase
    volumes:
      - ./proto:/proto
    depends_on:
      - user_db
    networks:
      - app_network

  user_db:
    image: mysql:8
    container_name: user_database
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: userdatabase
    ports:
      - "3306:3306"
    volumes:
      - ./tabu.sql:/docker-entrypoint-initdb.d/tabu.sql
      - mysqldata:/var/lib/mysql
    networks:
      - app_network

  user_grpc:
    build: ./UserManager
    container_name: user_grpc
    command: python grpc_server.py
    environment:
      MYSQL_HOST: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: userdatabase
    networks:
      - app_network
    depends_on:
      - user_db

  api_gateway:
    build: ./nginx
    container_name: api_gateway
    depends_on:
      - data_collector
      - user_manag
      - user_grpc
    ports:
      - "8080:80"
    networks:
      - app_network
      - app_data_network

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LOG_DIRS: "/tmp/kraft-logs"
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: "YnJhbmRvbi1rYWZrYS1rcmFmdA=="
    volumes:
      - ./data:/tmp/kraft-logs
    networks:
      - app_network
      - app_data_network

  alert_system:
    build: ./Alert
    container_name: alert_system
    depends_on:
      - kafka
      - data_collector

    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC_CONSUME: to-alert-system
      KAFKA_TOPIC_PRODUCE: to-notifier
    networks:
      - app_network
      - app_data_network

  notifier_system:
    build: ./Notify
    container_name: notifier_system
    depends_on:
      - kafka
      - alert_system
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC_CONSUME: to-notifier
      SMTP_SERVER: smtp_relay
      SMTP_PORT: 25

    networks:
      - app_network
      - app_data_network

  smtp_relay:
    image: namshi/smtp
    container_name: smtp_relay_email
    ports:
      - "2525:25"
    networks:
      - app_network

volumes:
  mysqldata:
  mysqldata2:

networks:
  app_network:
  app_data_network: