services:

  data_db:
    image: mysql:8.0
    container_name: data_database
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: datadatabase
    ports:
      - "3306:3306"
    volumes:
      - ./tab.sql:/docker-entrypoint-initdb.d/tab.sql
      - mysqldata2:/var/lib/mysql
    networks:
      - app_data_network

  data_collector:
    build: .
    container_name: data_collector
    depends_on:
      - data_db
    environment:
      DB_HOST: data_db
      DB_USER: user
      DB_PASS: pass
      DB_NAME: datadatabase 
    ports:
      - "5001:5001"
    networks:
      - app_data_network

volumes:
  mysqldata2:
networks:
  app_data_network: